### PR TITLE
Fix hashCode NullPointerException

### LINKED ISSUE #27: .hashCode of ordered maps with nil keys or values NPEs
I honestly do not know if this is a bug in timbre or in flatland, so I'm filing an issue with each. 

Timbre issue: https://github.com/ptaoussanis/timbre/issues/187

### PR DESCRIPTION
**Pull request by lvh**
Closes #27.

### CODE REVIEW

**Comment by lvh** [comment]
Sets turned out to not have this bug, but I added a test for it anyways.

File: src/flatland/ordered/map.clj [hunk 1]
```diff
@@ -86,7 +86,8 @@
     (.equiv this other))
   (hashCode [this]
     (reduce (fn [acc ^MapEntry e]
-              (let [k (.key e), v (.val e)]
+              (let [k (if-some [k (.key e)] k 0)
```
Comment (amalloy) [inline src/flatland/ordered/map.clj]: We shouldn't be substituting a 0 and then hashing that 0 - we should use the 0 instead of hashing at all, to remain compatible with `clojure.lang.APersistentMap/hashMap`. Your version works because `0` happens to hash to `0`, but we shouldn't rely on that non-guarantee.

Comment (lvh) [inline src/flatland/ordered/map.clj]: What does compatibility mean in this context? Why wouldn't 42 be OK?

Comment (amalloy) [inline src/flatland/ordered/map.clj]: Because `(= {nil nil} (ordered-map nil nil))` should be true, all clojure maps must use the same hashing strategy.

Comment (lvh) [inline src/flatland/ordered/map.clj]: OK, thanks; I'll add a unit test for that; I didn't realize IEquiv used hashCode as a heuristic. Or does that only matter when placing the maps in (associative) collections?

Comment (amalloy) [inline src/flatland/ordered/map.clj]: I'm not totally clear on what cases use hashCode and which use hasheq instead, but it's best to be the same for both - you can see that the original implementation of hashCode was an attempt to transliterate the existing java code (for clojure versions before it was exposed as a public static helper method).

Comment (lvh) [inline src/flatland/ordered/map.clj]: Am I right in assuming that was a typo and you're asking me to implement mapHash (not hashMap) as per here:

https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/APersistentMap.java#L103-L112

If so, coming right up :)

**Comment by lvh** [comment]
I have made the hashCode computation change as requested. I have not added a test because ostensibly that behavior was already tested; it didn't trigger a bug since as you mentioned `(.hashCode 0)` is already 0 anyway.

**Comment by amalloy** [comment]
Looking back at it now I'm not sure why we don't actually just delegate to c.l.APersistentMap/mapHash. since it does exactly what we need. I thought maybe it was a new method, but it's been around since 2010; anyone running a version of clojure older than that will just have to do without ordered maps.

**Comment by lvh** [comment]
I'm not sure how to implement that, I've never used delegating-deftype before. Can I just call APersistentMap/mapHash and type hint as appropriate?

**Comment by amalloy** [comment]
Right, that's all I meant. Call the existing static method. No type hints will be appropriate.

**Comment by lvh** [comment]
OK, made that change.

**Comment by lvh** [comment]
Is there anything else I can do to help get this PR merged? I believe I've addressed all comments.

**Comment by runejuhl** [comment]
Any possibility of this getting merged and a new version getting released anytime soon? I've been bitten by this a few times now which is a bit unfortunate.

This issue is a great stumbling block for newbies, as `ordered` may be used deep within the depths of libraries, and simply using [ptaoussanis/timbre](https://github.com/ptaoussanis/timbre) (re: https://github.com/ptaoussanis/timbre/issues/187) makes `timbre` respond with a NPE in a completely unexpected place.

**Comment by lewang** [comment]
bump on merging this and cutting a release?  @amalloy 

We use this in our YAML parser and it just bit us pretty hard.

**Comment by lewang** [comment]
tyvm @amalloy
